# fly.toml app configuration file generated for hello-world-3cants-app on 2026-03-17

app = "hello-world-3cants-app"
primary_region = "fra"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"
  memory = 512
